server:
  port: 8080

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:,vault://"
  datasource:
    url: jdbc:postgresql://db-auth:5432/auth
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  cloud:
    vault:
      uri: http://vault:8200/
      token: micro-wise
      scheme: http
      kv:
        enabled: true
        version: 2
        backend: secret
        profiles: ${spring.profiles.active}

logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  token:
    secret: ${jwt.token}
    expires: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://otel-collector-http:4318
        protocol: http/protobuf
        resource-attributes: 
          service.name: auth-service
          env: dev

otel:
  instrumentation:
    micrometer:
      enabled: true
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://otel-collector:4318
  resource:
    attributes:
      service.name: auth-service
      service: auth-service
      env: dev