apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname"-exporter . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_exporter.type }}
  ports:
    - port: {{ .Values.service_exporter.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}