apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}-grpc
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_grpc.type }}
  ports:
    - port: {{ .Values.service_grpc.port }}
      targetPort: {{ .Values.service_grpc.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}