{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "otel-collector.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: {{ .type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "otel-collector.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
  {{- if kindIs "slice" .ports }}
    {{- range .ports }}
  - name: {{ .name | default (printf "port-%d" .port) }}
    port: {{ .port }}
    targetPort: {{ .targetPort | default .port }}
    protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  {{- else }}
  - name: {{ .name | default (printf "port-%d" .ports) }}
    port: {{ .ports }}
    targetPort: {{ .ports }}
    protocol: TCP
  {{- end }}
---
{{- end }}
